services:
  db:
    image: postgis/postgis:15-3.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keptcarbon
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: keptcarbon
    ports:
      - '8000:8000'

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - '3000:80'

volumes:
  db-data:
